#!/usr/bin/env python

import imp
import sys
import os

cookie = 'b6e063a3e2722969a3880ebf89dcd0972dab9667f7b86350'

path = os.path.split(sys.argv[0])[0]
mod = imp.load_source('command', os.path.join(path, 'command.py'))
mod.execute('curl')
